### ISSUE TITLE
Remove meta data

### ISSUE THREAD

**Issue by jbeck22** [petersem/posterr#221]
Is it possible to remove the meta data at the bottom under the poster?

**Comment by petersem** [comment]
For on-demand, there is an option to hide header and footer sections. Custom pictures dont have header or footer, but everything else does. Other than that, you can create your own css in the /poster/custom/custom.css file to change how posterr looks. (changes in layout are not supported though, so it is up to you.) There isnt any support for hiding header and footer otherwise at the moment. 

![image](https://github.com/user-attachments/assets/501457eb-13b8-4e2c-b003-e1041cec5390)
![image](https://github.com/user-attachments/assets/fcd629de-82ee-403c-958e-a94469138cdb)
