### ISSUE TITLE
Rotate Screen vertically for vertically mounting the display

### ISSUE THREAD

**Issue by natget21** [petersem/posterr#227]
Hello,

I just checked out Poster, and it's really nice i love it. but I don't know if it supports it or not yet I didn't find it so is there an option to rotate the page so a normal screen that doesn't have a rotate option can be mounted vertically and display the poster vertically?

Thanks

**Comment by petersem** [comment]
@natget21 no support currently, but I'm trying to add this feature so that you could use browsers loaded on things like firesticks (which dont support rotation)

**Comment by petersem** [comment]
This feature is now available in version 1.20.0. I have also confirmed that Posterr can be loaded on a tv with an Amazon Firestick device. (I did side-load 'full screen browser' so that Posterr can run full screen.)
![image](https://github.com/user-attachments/assets/a419b23f-afa0-4f65-b417-b9756f49acbe)
