### ISSUE TITLE
Unable to resolve domain name

### ISSUE THREAD

**Issue by irodimus** [petersem/posterr#79]
When using Posterr 1.1.0 docker on a Synology DS1817+ NAS, I attempting to set Server IP or Domain Name (plex-comp.local) using the computer domain name but it is unable to be resolved and have to use the IP instead. Is there an environment variable that may be used to resolve my computer's domain name? If you have some different suggestions I could try, that would be appreciated.

**Comment by petersem** [comment]
Here's some different options: https://www.youtube.com/watch?v=i4xpYLASZ9U

Because this is not a Posterr issue, I will close this issue. Should you have further trouble, please re-open it.

**Comment by irodimus** [comment]
While I appreciate the help with this, the video link posted has nothing to do with the issue I was having. My issue had more to do with DNS not being resolved in the container for a computer on my network. The external computer can be found using an IP but not the domain name host.

**Comment by petersem** [comment]
> I understand this pertains to docker and Im sure it works when Posterr is running natively on a computer. I will leave it closed as I can get by with setting a static IP for the external computer for now.

@irodimus Gotcha. Yes, the containers are running on a separate internal Docker network from your normal computers. You will find this is the case for all containers that need to reference your NAS from within their networks. So whilst you can get to the Posterr web page from your PC using the .local address format, you can't use these as a reference inside any container. 

Because these .local names are variable by installation, there is nothing I can do about it.
